- 00-before-we-start.html
A small edit to a typo in the file. Hopefully I will get better with GitHub and be able to do more edits!
> Fixed typo in line 417 "or" --> "for"

- CONTRIBUTING.md
Based on twitter conversations, adding in information to bullet 2 that it's possible to make minor edits (like this one!) directly in GitHub.
> Adding in that can make minor edits on GitHub

- CONTRIBUTING.md
Adapted from text suggested by @ethanwhite  (https://github.com/datacarpentry/planning/issues/13)
> add guidelines for contributing datasets

- handout-script.R
- setup.R
> Use official combined dataset from repository

- 05-visualisation-ggplot2.Rmd
Hi,
[COMBINE](combine.org.au) taught the Data Carpentry R lessons in Sydney Australia last week (along with @lonsbio, @FPHeld, @steveped, @bobbledavidson and others). It was a big hit and attracted sponsorship from GigaScience, who are keen to get their own workshops up in China.
I had a bunch of suggestions for the ggplot2 lesson. Happy to split them up if you like some and not others. Briefly:
- Cut down the data cleaning/prep section. Students had only just learnt this, and still seemed bored hearing it again, even though we had just come back from a break. It also took valuable time from plotting and was already well covered in the previous session.
- Only create one cleaned data set `surveys_complete` and use it throughout the plotting exercises
- Notes on inheritance from the …
> Suggestions for ggplot lesson

- _includes/rSetup.html
I updated the language to clarify what it means to install binaries for CRAN
> Linux R instructions

- 00-before-we-start.Rmd
- 02-starting-with-data.Rmd
- 03-data-frames.Rmd
- 04-dplyr.Rmd
I went through the lessons in preparation for teaching [the Caltech DC workshop](https://github.com/datacarpentry/2015-11-23-caltech/wiki) and fixed a few minor issues. My R and Markdown fu is not awesome so comments and suggestions would be welcome.
ping @tracykteal => comments/merge
> misc fixes from going through the lessons

- 06-r-and-sql.Rmd
hey @emhart -- i'm going to teach this tomorrow. i'm psyched so thank you again for putting it together. A few thoughts - some of which are implemented in draft in this PR to begin discussion.
**Nested Joins**
1. i think the join three tables lesson is important. do we want to include it here OR in the SQL lessons. @ethanwhite @fmichonneau  any thoughts on this? i think it's a very good thing to add to the SQL lesson. then we use it here as a "query and plot data" type of activity.
2. related to this, you don't really need aliases when you do this. All you have to do is call tableName.field. the aliases are nice sometimes but i think they add additional complexity that you don't need to learn a 3 way join and it's complex to introduce both the nested join AND aliases in one go.
So this …
> updated sql lesson, edits, close con

- 05-visualisation-ggplot2.Rmd
Added challenges created for Rijk Zwaan workshop.
> Add two more challenges

- 01-intro-to-R.Rmd
- 04-dplyr.Rmd
For instructor checkout process
> Add challenge on vector types

- 05-visualization-ggplot2.Rmd
Added the modifications to the lesson 5 R-ecology.
Added cases:
- how to add white background to make graphs more readable
- how to change the orientation/size/colour of the axis text
- how to save plot to the file
> changes to 05-visualization-ggplot2.Rmd

- 05-visualization-ggplot2.Rmd
This is for my checkout session tomorrow ..
Cheers, Mark
> Add challenge violin plot

- 01-intro-to-R.Rmd
- 03-data-frames.Rmd
- 04-dplyr.Rmd
- Makefile
- index.md
* add paragraph about missing data
* add paragraph about conditional subsetting (needed for dplyr lesson)
* minor fixes to formatting
> Improve lessons

- 01-intro-to-R.html
I added a very brief mention of the fact that many standard R functions can act directly on vectors, with the idea of getting students to avoid (or unlearn) the habit of writing loops to step through vectors.
> Add a further vector example

- 01-intro-to-R.Rmd
This pull request is for fulfilling the requirement of the SWC/DC instructor certification. My name is Ye Li and my email is liye@umich.edu . I attended the training workshop between April 13-14 at Ann Arbor, Michigan.
I added examples to show how to use na related functions to extract complete cases. Thank you for reviewing my pull request.
> Add examples to show usage of na related functions

- 01-intro-to-R.Rmd
I added an NA challenge in the "Missing Data" section that builds on the "Vectors and data types" section.  I also changed a few things in the order of the previous challenge, because I was confused about the way it was set up on a first read.
> Update to 01-intro, add NA challenge

- 00-before-we-start.Rmd
I added information on Rstudio licensing policy with a web link to AGPL v3 and I also added a web link for R license GPL version 2.
> R and Rtudio Licensing policy with links to the corresponding GNU licenses

- 02-starting-with-data.Rmd
Introducing `table` does not seem necessary, as the main learning goal is to understand and manipulate factors.
Also: This is for SWC instructor training checkout from 2016-02-22-training-ucdavis
> Simplify and clarify factor-ordering challenge

- 00-before-we-start.Rmd
In the first lesson towards the end we talk about how to ask for help from the community e.g. Stackoverflow, R mailing list etc. I have found a few small typos and also added two links on [How to write a reproducible example](http://adv-r.had.co.nz/Reproducibility.html) (this is a nice article from Hadley Wickham) and [How to ask a question on Stackoverflow](http://stackoverflow.com/help/how-to-ask) as I thought this would be a useful reference for newbies.
This is also to fulfil part I of the checkout procedure for the DC instructors training (attended Cambridge 19/20th September).
> Added information write reproducible examples

- 04-dplyr.Rmd
- 05-visualization-ggplot2.Rmd
- 06-r-and-sql.Rmd
In this PR I modify the learning objectives for lessons
04-dplyr
05-ggplot2
06-SQL
The main objective was to add some clarity by elaborating on each objective so that a non expert could read them and hopefully understand what they are going to do without needing to know only R lingo. In essence these are slight extensions on the existing objectives 
Best
Lachlan
PS. Pull request for Instructor Traning, Data Carpentry
> Modifying learning objectives lessons 04, 05, 06

- 05-visualization-ggplot2.Rmd
Added a bullet point (L203-206) to the challenge about boxplots. This extended challenges requires students to use previous knowledge about integers and factors to assign colors to the graph correctly.
> adding-challenge-05-visualization-ggplot2.Rmd

- 03-data-frames.Rmd
- 05-visualization-ggplot2.Rmd
> edited learning objectives to be more specific and task focused

- 01-intro-to-R.Rmd
> change "error" to "warning"

- 04-dplyr.Rmd
I've corrected a few typos, added clarifying text a few places, and created a new challenge. Open to feedback if you'd like any changes prior to merging!
> Some hopefully helpful updates to dplyr lesson

- 01-intro-to-R.Rmd
This is being submitted as part of instructor training.
> missing values read in

- 05-visualization-ggplot2.Rmd
It looks like this sentence referenced a plot that was removed a few commits ago.
> Removed the first sentence after loading pacakges,

- 04-dplyr.Rmd
I understand that a goal across SWC and DC lessons is to make learning objectives more measurable and framed in terms of observables. I tried to do that here using verbs that fit more clearly into Blooms taxonomy, rather than 'know' or 'be able to'.
> Edited learning objectives for episode 4

- 00-before-we-start.Rmd
@aurielfournier @fmichonneau 
Data Carpentry wants to improve our assessment efforts. To do this we want to improve the learning objectives for all of our lessons so that they are measurable. I'm proposing slight changes to the LOs for all of the ecology lessons.
> Revised learning objectives

- 00-before-we-start.Rmd
- 01-intro-to-R.Rmd
- 02-starting-with-data.Rmd
"Such they can obtain" doesn't sound right. Simplified the sentence.
> Improving clarity

- 05-visualization-ggplot2.Rmd
I am creating this pull request to improve the information provided in this lesson. Every time I teach ggplot2 at the university, students often struggle with the position of the '+' sign. Therefore, I thought it would be nice to bring it explicitly here. This pull request is part of my instructor training checkout.
> adding information on the use of the plus sign

- 00-before-we-start.Rmd
+Fixed sub-list formatting (need 4 spaces not 2)
+Added suggestion to google search when looking for a function to do X
> formatting and google comment

- 05-visualization-ggplot2.Rmd
Hi, I added a challenge question about using hexagonal binning in the visualization component of R-ecology lesson. I hope that it is useful & usable. If I should revise the exercise or reformat it, please let me know.
Thanks,
fred
> R ecology hexbin

- 05-visualization-ggplot2.Rmd
add info about themes and other customizations available for ggplot2
> [fix #170] add call out box about ggplot2 themes and extensions

- 03-data-frames.Rmd
First iteration of the revision of the data frame lesson.
Once the PR about factors will be merged, there will be other things to move around.
> [fix #169] revise data frame lesson

- 01-intro-to-R.Rmd
I revised some wording in the missing data section of the Intro to R file and added a new challenge to address issue #166.
> Revise missing data

- instructor_notes.md
Creating the outline for the instructor_notes.md file.
Obviously everything still needs to be filled in but this follows the guidelines and is a start.
> Create instructor_notes.md outline

- 01-intro-to-R.Rmd
As discussed, I've made the changes to the documentation introducing the term _coercion_ into the guide. Thanks!
> Modified hierarchy section (issue #193)

- 04-visualization-ggplot2.Rmd
- 05-r-and-databases.Rmd
don't render package loading messages and don't use . in variable names.
> Minor adjustments

- 05-r-and-databases.Rmd
It's never explained that surveys is now missing some columns that need to be added back in my joins. Also some better wording for the challenges.
> Clarification for challenges in lesson 5

- README.md
Hi,
Following @fmichonneau comments in #182 I changed the README.md file.
The CONTRIBUTING.md file should also be updated, should I do it here or in another PR?
Thanks
> Update README file #182

- 02-starting-with-data.Rmd
I have removed some redundancies in the learning objectives, rearranged
items to give a more logical structure and cleaned the terminology to
make it more consistent
>  refine learning objectives

- 01-intro-to-R.Rmd
fixed broken link: https://github.com/datacarpentry/R-ecology-lesson/issues/210
> [fix #210] broken google style guide link

- 00-before-we-start.Rmd
- 01-intro-to-R.Rmd
- 05-r-and-databases.Rmd
- index.Rmd
Minor revisions of typos and grammar.
> Fixed typos and grammar

- 05-r-and-databases.Rmd
Added missing "not", broke up a few long sentences and fixed typos (Issue #186).
> Fixed grammar and typos in 05-r-and-databases.Rmd

- 03-dplyr.Rmd
As suggested in issue 225, I further specified that filter is used for selecting rows based on certain  criteria. 
This is my first PR so let me know if I've done anything wrong!
> further specify use of filter - issue 225

- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
Minor wording changes which should allow for the closing of issues 226 and 227 of the repo?
> addressing issues 226 and 227

- 00-before-we-start.Rmd
- 00-before-we-start.html
Just mentioning it at the end (More resources section) in case anyone wants to try
> Mentioning reprex package to create reproducible examples

- 00-before-we-start.Rmd
> Fixed grammar and typos in 00-before-we-start.Rmd

- 04-visualization-ggplot2.Rmd
#186 
http://www.datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html
> minor wording changes 04-visualization-ggplot2.Rmd

- 05-r-and-databases.Rmd
#186 
http://www.datacarpentry.org/R-ecology-lesson/05-r-and-databases.html
> minor wording changes 05-r-and-databases.Rmd

- 00-before-we-start.Rmd
- 03-dplyr.Rmd
* Based one the suggestions of @fmichonneau and @dvanic I made textual changes to the before you begin
* Simplified the wording about dplyr.
> made text changes suggested in #214

- 00-before-we-start.Rmd
- 03-dplyr.Rmd
> Reworded intro for clarity about R

- 00-before-we-start.Rmd
- 01-intro-to-R.Rmd
Ensure that learning objective "working directory"  is in the right lesson to match content. Addresses #222
> moved the learning objectives around 

- 04-visualization-ggplot2.Rmd
> dataframe -> data frame, for #242

- 01-intro-to-r.Rmd
- 02-starting-with-data.Rmd
- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
closes #242
note this conflicts with #251 which partially-fixes above-referenced issue
> Make 'dataset' and 'data frame' usage consistent

- CONTRIBUTING.md
together with fixes by @ha0ye in 61e2b306 closes #205
> Fix link to LICENSE.Rmd

- 01-intro-to-r.Rmd
- 02-starting-with-data.Rmd
- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
- 05-r-and-databases.Rmd
I modified grammar and punctuation in all of the R-ecology-lesson segments. There was also some redundant text and I provided a suggested edit.
> fixing-typos-r-ecology-lesson

- 02-starting-with-data.Rmd
As per my discussion with @fmichonneau, I've added a brief demonstration of how {lubridate} can be used to convert date information from date components in separate columns to a POSIXct vector that can be added to a data frame as a new column called "date".
It was suggested that a plot incorporating date may be used to motivate this information; for the moment I've just included a brief how-to at the end of the Starting with Data segment of the lesson. I'd be more than happy to draft a complimentary piece for the Visualization segment, which could be separate or include the piece I've added here.
Looking forward to feedback and hoping to become more involved in SC and DC! : )
P.S. This is my first time creating a branch, modifying content, and creating a pull request - I apologize if its …
> added formatting dates in R

- 03-dplyr.Rmd
- 03-dplyr.html
- site_libs/navigation-1.1/tabsets.js
So, this is an attempt at adding a short intro to `tidyr` as discussed [here](https://github.com/datacarpentry/R-ecology-lesson/issues/95) in the issues. I do worry this will add too much, but, feel very strongly given my own experiences as a quantitative ecologist that a working knowledge of gather and spread is essential.
I've tried to find the right place to slot it in, but I can see other options - separate small lesson and/or moving data writing to somewhere else.
Let me know what y'all think, but I do think this is important!
> Add tidyr to dplyr lesson

- 00-before-we-start.Rmd
I'm using an RStudio daily, and I see "New project" rather than "Empty Project"
> Update to RStudio new project dialogue text

- 00-before-we-start.Rmd
Not sure whether I should have rather opened an issue. 😉 In any case Jenny's presentation about `reprex` and reproducible examples in general in that call was great so maybe useful to add.
> Adds a further resource about reprex

- 01-intro-to-r.Rmd
- 03-dplyr.Rmd
I have made some small revisions in 01-intro-to-r.Rmd and 03-dplyr.Rmd.
Please see files and commits for details.
> Pipe mutate update

- 04-visualization-ggplot2.Rmd
---
I added a sentence in the preamble about data frame format that ggplot likes. I have always found that if you understand that ggplot really prefers data in 'long' format, plotting becomes a breeze.
---
> Long data frame format described in preamble in ggplot lesson

- 00-before-we-start.Rmd
- 01-intro-to-r.Rmd
* RStudio IDE cheatsheet link
* More comprehensive Hadley Wickham's style guide
> A few links

- 02-starting-with-data.Rmd
Extra "the", extra full stop, extra "date", spaces around "<-", no capital for the class "date".
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or …
> typos and style

- 03-dplyr.Rmd
- code-handout.R
minor typos in reshape challenge (number 3. and 4.) were fixed in 03-dplyr.Rmd as well as in code-handout.R
> fixed typos in reshape challenge in dplyr lesson

- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
- code-handout.R
I did some updates on the ggplot2 lesson to improve clarity, see for details below: 
- added information that ggplot2 is included in tidyverse
- added data load step in case someone had closed RStudio in between or had deleted workspace
- added a very short challenge before boxplot (maybe too simple?)
- removed `group` statement in aes() when `color` is introduced, since using `color` automatically groups data (removed all unnecessary `group` statements in later plots)
- adjusted text regarding the use of group/color accordingly
- removed colour=species_id from faceted plot
- added colour=sex in second faceted plot
- replaced panel.grid.major/minor.x/y with panel.grid (this way it is much shorter for the same result and less overwhelming)
- removed part where colour for sex is added …
> update ggplot lesson to improve clarity

- 04-visualization-ggplot2.Rmd
> Add clarification to the intro of ggplot2 and a few geom examples 

- 04-visualization-ggplot2.Rmd
changed read.csv to read_csv , since we are teaching with tidyverse pkg, we should stick with tidyverse syntax and create tibbles
added library(hexbin) after installation of pkg.
added () after tally function
> changed read.csv to read_csv (tidyverse way)

- 01-intro-to-r.Rmd
As part of instructor checkout procedure, I added a lesson objective in
R-intro to add that the learner should learn how to name objects. This
is covered in the lesson but not as a point in the objectives which I
think is important.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson …
> Added a lesson objective

- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
As discussed, changed only the Manipulating and analyzing data with dplyr; Exporting data.
* Added comments about the tidyverse pkg
* changed read.csv to read_csv
* changed write.csv to write _csv
(Note: will change other lessons once these changes here are approved)
> Proposed fixes

- 01-intro-to-r.Rmd
- 02-starting-with-data.Rmd
- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
This PR addresses the following things:
- Minor typos
- Consistently use double quotes for strings
- Consistently use spaces around `=`
> Consistency fixes

- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
Very small typos/stylistic points. (I think "datapoints" should be "data points", feel free to disagree ...)
> minor typos/style

- 01-intro-to-r.Rmd
@fmichonneau @aurielfournier Learning objectives were improved last year (see more on this [document](https://docs.google.com/document/d/1NU5zHNeoU327yiDMrFHm_vYYSTFl98NVTrcqptpA6RA/edit)). I updated the language to make the objectives more clear. Please let me know if this update is inconsistent with what learners should be able to do by the end of the module.
> Fixed typo and improved learning objectives

- 03-dplyr.Rmd
I added examples of intermediate steps and nested functions, as discussed in issue #327. (I also modified text to clarify that `read_csv` is from the `readr` package (not dplyr) - since that wasn't discussed, I can remove it if needed!)
> Add examples of intermediate steps + nested functions

- 02-starting-with-data.Rmd
- 03-dplyr.Rmd
style/grammar fixes only, nothing more controversial ...
> Bbolker fix1 style

- 02-starting-with-data.Rmd
This pull request is in reference to issue #344. 
Please edit as you see fit.  
thanks - Robin
> modified text to reflect no warning message from lubridate parse failure

- instructor-notes.md
At my last workshop we had extensive issues (more then half of computers) with problems installing R/R packages. Unfortunately these issues were not realized until we were into the first days lessons, and again at the start of day 2. I don't have a solution for this, but wanted to add some text to let instructors know to be on the look out for this and ask about it if a learner is having issues installing an R package/R itself.
> adding in emphasis that things be installed locally

- 02-starting-with-data.Rmd
> adding more tidyverse detail

- needed_packages.R
By giving them a comprehensive list of what packages are needed for these lessons.
Adding onto #336
> to aid instructors w/ R package install issues

- instructor-notes.md
adding link to instructor guidelines so that they can find the list of all the necessary packages.
> adding link to necessary_packages.R

- 02-starting-with-data.Rmd
@aurielfournier  could you please review this?
I suggest we change the narrative a little so we don't rely on the bug currently affecting `ymd`. We use the function, check it produces the correct output, and investigate why it doesn't. It seems like a realistic approach that is good to demonstrate and teach. Let me know what you think.
> fix confusion around parsing invalid dates

- instructor-notes.md
Added mention of tidyr to instructor training guide on the main tidyr functions used in this lesson.
Fixes: issue #269
> add mention of tidyr to instructor guide

- footer.html
> Updated to current year

- 04-visualization-ggplot2.Rmd
There was no elaboration for adding a vector as an input for the color argument in ggplot, I added a further explanation that may help.
> Added elaboration to placing a vector as an input to color argument in ggplot

- 04-visualization-ggplot2.Rmd
Hello,
This is my submission for the first checkout exercise of the SWC/DC instructor training.
I have fixed some typos and formatting inconsistencies in the lesson Rmd, and I have added a solution to the challenge in section "Building your plots iteratively".
> corrections and challenge answer for ggplot2 lesson

- 02-starting-with-data.Rmd
Add some comments on the use of read.table and how similar result can be achieved as with the read.csv function.
> Update the note section 

- 02-starting-with-data.Rmd
Correct a few mistakes, in particular:
- loading the tidyverse does not load all the packages. Lubridate, for instance, does not get loaded by `library(tidyverse)`
- unnecessary combine function `c` in the indexing section
- several small grammar or syntax mistakes
Suggest wording changes:
- cut unnecessary words
One problem not addressed (I will open an issue as I don't know rmarkdown enough to address it myself-I use org mode, not rmarkdown in my own projects):
- text answer appears at the bottom of the question in the last challenge
> Correct mistakes and suggest wording changes

- 02-starting-with-data.Rmd
During instructor training we discussed the learning objective 'manipulate categorical data' and found it quite vague. The factors section in this lesson is quite detailed and is clearly trying to get across multiple key points. I suggest changing learning objectives to include these points.
> Make factor learning objectives more specific.

- 02-starting-with-data.Rmd
Students may expect the code chunk to just work. To avoid frustration, make this code chunk reproducible by first creating data/.
> Create data/ for a reproducible workflow.

- 01-visualizing-ggplot.Rmd
- 02-intro-to-r.Rmd
- 03-starting-with-data.Rmd
- 04-dplyr.Rmd
added title in some lessons, added author in the beginning and changed formatting of title.
> Tidyverse first

- 03-dplyr.Rmd
just a missing closing parenthesis. Sorry about the small pull requests!
> close markdown hyperlink

- 03-dplyr.Rmd
The challenge states: "Also add the number of observations (hint: see `?n`)"
I assume what is expected is to create an extra variable in `summarize()` that is simply equal to `n()`.
> add n variable like asked in challenge

- 03-dplyr.Rmd
I am not sure if that error is due to a recent change in dplyr, but the rows are ordered so that the NA rows are at the bottom.
At least, this is what happens on my system, with the packages updated today.
Could someone confirm?
> "first rows" -> "last few rows"

- 04-visualization-ggplot2.Rmd
> fix answer to challenge 2

- 02-starting-with-data.Rmd
> clearer wording in "Indexing & Subsetting..." challenge

- 04-visualization-ggplot2.Rmd
Reverts datacarpentry/R-ecology-lesson#423
> Revert "Changed 04-visualization-ggplot2.Rmd to remove unecessary installatio…"

- 00-before-we-start.Rmd
Added punctuation and info to figure headings. Changed some typos/grammar.
> fix grammar and small edits in before we start R ecology lesson

- 04-visualization-ggplot2.Rmd
This is my suggested fix for my suggested issue #421
mapping= is added to all uses of ggplot where data= is used.
ggplot template is surrounded by ` ``` ``` `.
> Use mapping=aes(...) in ggplot section.

- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
These are some thoughts for changes following our recent [Data Carpentry in R in Cambridge 28th-28th June 2018](https://tavareshugo.github.io/2018-06-28-cambridge/). Please follow commit comments.
> rewording words/sentences and adding small changes to the code

- index.Rmd
for consistency with lessons page
> update lesson title

- 00-before-we-start.Rmd
> Fixes issue 449

- 04-visualization-ggplot2.Rmd
Hi!
I would like to do a pull request of the issue #437 in which we tried to clarify differences and similarities when defining colors in the mapping vs in a geom layer. 
Thanks for this great Git repo! 
Sergio.
> Differences between defining colors in mapping vs geom #437

- 03-starting-with-data.Rmd
- 04-dplyr.Rmd
Merge in PR #459 and #478 into tidyverse-first branch
> Merge in PR #459 and #478 into tidyverse-first branch

- 04-visualization-ggplot2.Rmd
number of individuals instead of species as pointed by 
https://github.com/datacarpentry/R-ecology-lesson/issues/452
> number of individuals instead of species

- 05-r-and-databases.Rmd
was tbl("mammals", species),
which gives an error : 
Error in UseMethod("as.sql") : 
no applicable method for 'as.sql' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
> tbl(mammals, "species")

- 02-starting-with-data.Rmd
Additional solution using `complete.cases` is aligned with training content immediately preceding.
> Clarifications in the Factors challenge

- 01-intro-to-r.Rmd
Additional solution using `complete.cases` is aligned with training content immediately preceding.
> Added clarification and another solution to missing data challenge

- 05-r-and-databases.Rmd
1. downloaded the species, plots, and surveys data into the data folder. 
2. imported tidyverse, to be able to use the read_csv() function
3. changed output file to "data_output/portal-database-output.sqlite" to be consistent with other lessons
4. added "copy_to(my_db, species)" because it was missing
> updated writing databases section

- 02-starting-with-data.Rmd
Added a  learning objective for use of subsetting since there is a seciton that teaches this but does not have a stated objective.
> Update learning objectives in 02-starting-with-data.Rmd

- 04-visualization-ggplot2.Rmd
Some updates for URLs that have recently changed. Don't panic, the old URLs still work and, as in the case of links to the ggplot2 docs, are re-directed!
> Url updates

- 04-visualization-ggplot2.Rmd
> Addresses issue #527

- 02-starting-with-data.Rmd
Add text in the note section about csv file to invite users to pay attention of other attributes of csv files:
- character encoding (important for international users);
- control characters used for line ending;
- date format (if note splitter into three variables)
- presence of unexpected newlines
> Update 02-starting-with-data.Rmd for csv attributes

- 05-r-and-databases.Rmd
Same as https://github.com/datacarpentry/genomics-r-intro/pull/37 ;-)
> Canonicalize CRAN link

- 03-dplyr.Rmd
- index.Rmd
A few quick suggested fixes, partly in response to #536 and also from some personal notes.
> Install packages fixes

- README.md
updating based on Data Carpentry instructor training checkout, Melissa Moreno, melimore86@ufl.edu, https://carpentries.github.io/instructor-training/20-checkout/index.html
> updating, instructor training checkout

- 02-starting-with-data.Rmd
Typo fixes from my previous contribution
---
> Add csv file attributes

- AUTHORS
- CITATION.Rmd
and CITATION script to match latest Zenodo citation info.
https://carpentries.topicbox.com/groups/maintainers/Ta171093e66e6d451-M3082d0df6d8fdf43f15d6f6a/lesson-release-and-updating-citation-info
> Updated AUTHORS list

- 01-intro-to-r.Rmd
Removed unnecessary comma as noted by @kimokeefe
Closes #554
> Corrects typo, #554

- 03-dplyr.Rmd
Multiplying by 2 seems to be a less realistic example than the [one we have in 01-intro-to-r.Rmd](https://github.com/datacarpentry/R-ecology-lesson/blob/ed1c4aeac050cb49f7c01f9a2889a7e9555b7309/01-intro-to-r.Rmd#L123). Should we re-use that one?
> Improve first mutate example

- 03-dplyr.Rmd
Add an explanation for column specification in read_csv.
> explain read_csv column parsing

- 03-dplyr.Rmd
> Rename last rich_time occurence

- instructor-notes.md
I added instructor notes to the data manipulation section about including the select() command to make it easier for learners to see the changed columns.
> added instructor notes to data manipulation section

- 04-visualization-ggplot2.Rmd
Corrected typo in challenge text. 
See issue #588
> Corrected typo in 04-visualization-ggplot2.Rmd

- instructor-notes.md
Adding contribution from Cami about setting colors using color HEX code in the visualization chapter to instructor notes, see PR #600
> Contribution from @camillanovaglio, see PR #600

- 01-intro-to-r.Rmd
- 03-dplyr.Rmd
The `r` blocks with the challenge questions texts are sometimes out-of-sync with the `{.challenge}` boxes. Here's one example. Since I'm on vacation for two weeks, anyone who wants to continue this, is welcome to it :-)
Follow-ups to: 041b9a97
> Align handout comments with challenges

- 04-visualization-ggplot2.Rmd
I have tried to address the issue and added a small explanation and a couple of examples of how the pipe operator can be integrated with ggplot2 obtaining the same results and in the previous plot (where no pipe is used)
> [fix #583] explain how to combine pipe operator for ggplot

- 00-before-we-start.Rmd
- 01-intro-to-r.Rmd
I have added a brief explanation of workspace to make it easily understood by new users. I have also fixed comments in lines 535-540.
> Explained what workspace is

- 01-intro-to-r.Rmd
> include instructions for saving script

- 05-r-and-databases.Rmd
Especially useful for those not going through the whole curriculum and in the same order
> turned referal to SQL lesson into link

- 03-dplyr.Rmd
This lesson is very useful too for people not ecologists.
With little subtle changes this can be improved, this is an example.
> explain how genus and genera relate

- 01-intro-to-r.Rmd
> to make it easier to remember

- 01-intro-to-r.Rmd
Also makes saying things in the order they're written.
> shorter pronounciation of <-

- 01-intro-to-r.Rmd
#632 Changed paragraph to bulleted list for ease of instruction.
> [fix #632] add bulleted list to rules for naming objects

- 01-intro-to-r.Rmd
The more complicated examples had no explanatory comments.
I have also added another "cat" to the animals vector, so that it becomes clear that %in% matches multiple times.
> Updated example for logical indexing of vectors, closes #644

- 02-starting-with-data.Rmd
The reordering of levels requested in the challenge was not necessary because the levels were already in the correct order
closes #669
> Alter barplot challenge

- README.md
Updated maintainers list in README.md
> update maintainers list

- instructor-notes.md
> addresses issue #688

- 01-intro-to-r.Rmd
> fixes typo mentioned in issue #686

- 02-starting-with-data.Rmd
> Add missing line in answer to match exercise

- instructor-notes.md
Added character vector to Required Packages
> Added character vector to Required Packages (#701)

- 02-starting-with-data.Rmd
I edited a comment from 02-starting-with-data.Rmd following issue #673 to clarify data formats
> Small edit to comment in Indexing and subsetting data frames 

- instructor-notes.md
I added a line within the "narrative" comments for *Manipulating data*, addressing view() versus View().
> Minor update to Instructor-notes issue #685

- 04-visualization-ggplot2.Rmd
> fix-genus-species-confusion

- 00-before-we-start.Rmd
- index.Rmd
- instructor-notes.md
> replace 'here' link texts with more accessible text

- 02-starting-with-data.Rmd
This episode (Starting with data) explains what packages are, how to install and load them, but this was missing from the Learning Objectives. In this pull request I have added the topic as a new line in the learning objectives.
> added install/load packages to learning objectives

- 00-before-we-start.Rmd
>  soften recommendation to not save workspace on exit

- 01-intro-to-r.Rmd
- 02-starting-with-data.Rmd
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck …
> Fix typos for data-analysis-and-visualization-in-R lesson

- 03-dplyr.Rmd
We noticed this in the workshop I taught yesterday.  @sawildman filed an issue.  Think this PR should implement the change he suggested.
based on issue #726 from @sawildman
Closes #726
> Added in current units

- 02-starting-with-data.Rmd
> fix typos, closes #732

- index.Rmd
This would close #240
- I wonder if the Preparations section is the  right place for this information or if this would fit better in "Before we start", maybe before "organizing your working directory"
- Is it too detailed? 
- is anything missing?
> guidelines for managing package library, closes #240

- 02-starting-with-data.Rmd
- instructor-notes.md
Implementing suggestions from @vanilink in issue #710, closes #710
> emphasize importance of using read_csv not read.csv

- 02-starting-with-data.Rmd
- instructor-notes.md
The terms "plot" and "genus" cause some confusion for non-ecologists. Here are some small changes to the instructor notes and a tiny change to the lesson to clarify the terminlology.
closes #552
> clarify ecological terminology

- 05-r-and-databases.Rmd
Grouping by plot was missing in SQL version of challenge solution
Closes #731
> fix error in SQL solution

- 05-r-and-databases.Rmd
Update broken link due to page move.
- Old link: https://dplyr.tidyverse.org/reference/join.html
- New link: https://dplyr.tidyverse.org/reference/mutate-joins.html
Resolve #757
> Update broken link due to page move

- 02-starting-with-data.Rmd
> remove inaccurate description of expected output of read_csv().

- 02-starting-with-data.Rmd
- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
I updated the remaining rstudio cheat sheet links that were broken.
> fixed broken cheat sheet links

- 00-before-we-start.Rmd
Per issue #743:
1. Listed out the panes to make it easier to read
2. Added a sentence about adjusting colors and size
> Added accessibility options to resolve #743

- 02-starting-with-data.Rmd
Hello,
I am offering potential responses to the answered questions discussed in issue #763.  A typo was also corrected in the first sentence under the _Formatting dates_ heading of the [Starting with data](https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html) episode.
Denisse
> Possible solution to issue 763

- 02-starting-with-data.Rmd
Corrects a minor rendering issue
> Added a space to address formatting related to #776

- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
---
Thanks for contributing! If this contribution is for instructor training, please send an email to instructor.training@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate …
> Typo fixes

- 02-starting-with-data.Rmd
Hi, I'm made a fix based on the suggestion by @Teebusch for issue #797. 
Dear reviewers, kindly merge the changes, if it's alright
p.s. it's my first time doing it for [checkout](https://carpentries.github.io/instructor-training/checkout/index.html).  I saw that the issue was tagged with "help wanted" and decided to go ahead to make the changes.
> [EJYS] Fix as suggested in issue 797

- index.Rmd
Updated instructions for install for the three operating systems to bring them into compliance with the new RStudio numbering system.
fix #791
> Clarified install instructions in index.Rmd

- before_body.html
This fixes the date to show that the beta phase for this lesson will end in 2023, not 2022.
> fix date of beta phase end

- 04-visualization-ggplot2.Rmd
Partial fix to https://github.com/datacarpentry/R-ecology-lesson/pull/834
> replace blocked link

- before_body.html
this reflects the updated schedule of the workbench beta phase as outlined in https://carpentries.org/blog/2022/12/dovetail-12/
Additionally, please let me know if you would like me to reset your test repository at https://github.com/fishtree-attempt/R-ecology-lesson.
Best,
Zhian
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203516117412888
> Update beta phase timeline

- 02-starting-with-data.Rmd
added a blank line before the bulleted list in episode 2 so that it renders correctly.
> add blank line before bulleted list; fix #824

- .zenodo.json
Updates the `.zenodo.json` file with the latest list of contributors who have given permission to be included in lesson publications.
> update contributor info

- learners/setup.md
Fix #920.
It is difficult to come up with something that precise for the general case as linux distributions come in many different flavours but I believe this PR is already a net improvement compared to the current situation, which gives invalid instructions.
> Fix Linux install instructions
