_includes/rSetup.html
The workshop uses `dplyr`, which requires R>=3.1.2, yet some distribution repos (e.g. the default Ubuntu 14.04 repo) only provide older versions of R.  Added note in rSetup that might need to use CRAN packages to get R>=3.1.2.
=> Warn that need R >=3.1.2

index.md
Fix the link: http://www.datacarpentry.org/R-ecology/05-visualisation-ggplot2.html that was giving a 404 error to http://www.datacarpentry.org/R-ecology/05-visualization-ggplot2.html
=> Link form index page to lesson 05 not working

.mailmap, .update-copyright.conf, 04-dplyr.Rmd, 05-visualization-ggplot2.Rmd, AUTHORS, CONTRIBUTORS.md
This is an example of what was discussed in datacarpentry/lesson-template#22 and could be generalized to other lessons. The AUTHORS file is generated automatically by the [update-copyright python package](https://pypi.python.org/pypi/update-copyright/) but the script needs to be run manually. Currently, SWC runs the script before major releases of the lessons. Here, it could be added to the Makefile, but it would require that the package is installed for it to work.
=> consolidate author info and use update-copyright.py to generate AUTHORS

03-data-frames.Rmd
1. I removed the reference to the `cbind` and `rbind` commands because they
produce counterintuitive results that are probably not worth discussing
here. Specifically, both functions produce matrices, meaning that they
coerce vectors to a common data type. In the given example, this means that
both `colors` and `counts` columns are converted to factors, which is
**not** intuitive behavior. Therefore, I personally strongly advise against
using `cbind()` to make `data.frame`s from scratch (though there's nothing
wrong with using these functions to add rows or columns to an existing
`data.frame`, since that uses a different method of `cbind`).
2. I added some comments and (brief) mention of the fact that different syntax
for subsetting a `data.frame` produces different results. Personally, I …
=> Minor revisions to data.frame lesson

01-intro-to-R.Rmd, 03-data-frames.Rmd, 04-dplyr.Rmd, 06-r-and-sql.Rmd
Fixed a couple of typos. The `wgt` to `weight` change is important.
As is the addition of the missing backtick which broke styling.
I kept each fix in a single commit so you can cherry pick but I can also stash them if desired.
=> Fix some typos

00-before-we-start.Rmd
When reading the section in the first lesson ["Before we start"](https://github.com/lmsimp/R-ecology-lesson/blob/help-info/00-before-we-start.Rmd) I have found inconsistent use of the capitalisation of RStudio. I have fixed this in this PR. 
I have also added how to customise the pane layout of RStudio. I found that some attendees don't always have the default setup and knowing how to change this to match the instructors setup (if they so wish) is useful. As this is only adding a few words after the first mention of customisation of the panes, I included it in this branch as it is part of the same section as the typos I found. Hopefully this is clear in the two commits in this branch of this PR.
This is also to fulfil part I of the checkout procedure for the DC instructors training …
=> Capitalisation of RStudio and Rstudio

07-dplyr-and-databases.Rmd
This is a first proposal with 07-dplyr-and-databases.Rmd, an alternative to / replacement of lesson `06-r-and-sql.Rmd` It addresses issue / contribution request #126 . I am happy to improve the proposal, if it is considered useful at all. Any feedback is very welcome.
- I tried to stick to the existing lesson 06 as closely as possible, but using dplyr shifts the learning objectives from writing SQL to understanding the concept of lazy evaluation in R.
- The most difficult challenges of lesson 06 turned out to be very straightforward using dplyr's notation.
- There were some reference to a GUI (firefox plugin) to examine SQLite databases, which I believe are largely outdated by now. I have removed them, but am happy to add them back in if necessary. 
- The database creation section also …
=> First proposal for a dplyr-database lesson, addressing issue 126

02-starting-with-data.Rmd
I'm seeing `date` rather than `POSIXct`, using lubridate_1.6.0
```
library(lubridate)
surveys$date <- ymd(paste(surveys$year, 
surveys$month, 
surveys$day, 
sep = "-"))
str(surveys)
'data.frame':	34786 obs. of  14 variables:
$ record_id      : int  1 72 224 266 349 363 435 506 588 661 ...
$ month          : int  7 8 9 10 11 11 12 1 2 3 ...
$ day            : int  16 19 13 16 12 12 10 8 18 11 ...
$ year           : int  1977 1977 1977 1977 1977 1977 1977 1978 1978 1978 ...
$ plot_id        : int  2 2 2 2 2 2 2 2 2 2 ...
$ species_id     : Factor w/ 48 levels "AB","AH","AS",..: 16 16 16 16 16 16 16 16 16 16 ...
$ sex            : Factor w/ 3 levels "","F","M": 3 3 1 1 1 1 1 1 3 1 ...
$ hindfoot_length: int  32 31 NA NA NA NA NA NA NA NA ...
$ weight         : int  NA NA NA NA NA NA NA NA …
```
=> I'm seeing `date` rather than `POSIXct`

02-starting-with-data.Rmd, CONTRIBUTING.Rmd
Suggested edit (as part of the instructor training checkout): I've added a blurb on how to install the `lubridate` package, if one gets an error prompt that it is missing.
=> Added note on how to install missing package

02-starting-with-data.Rmd
Changed order of examples explaining subsetting dataframes. The section now starts with explaining the simple concept of extracting a value based on its location in the dataframe, therefore showing that the first part of the command refers to the row and the second to the column. Then it moves on to subsetting whole columns in different ways.
This is a part of my instructor training checkout.
=> Update to subsetting 02-starting-with-data.Rmd

01-intro-to-r.Rmd
In response to issue #274 , I clarified the explanation of an atomic vector when it is first encountered in the lesson. I also added in text to let the reader know that numeric and double are synonymous terms. This is important because when checking the type of a vector in R, it outputs "double" which could be confusing if a reader has never encountered the term. I also added in notes for the function typeof() for checking the type of a vector. Further, I fixed the text confusion under the examples in the missing data section, changing it from reading "the output is atomic" to "the output is an atomic vector of type numeric (or double)".
=> Atomic vector explanations in 01-intro-to-r.Rmd

02-starting-with-data.Rmd
Clarified that `head_surveys <- surveys[1:6, ]` is equivalent to `to head_surveys <- head(surveys)`.
Added a brief explanation about why `as.numeric(f)` is wrong
Capitalised the start of two comments for consistency since the others start with capital letters
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be …
=> Clarify head() and as.numeric()

05-r-and-databases.Rmd
To list the tables and get an output that reflects the text in lesson, use `src_dbi()`
The current code just calls mammals which results in a different output, and because sentences following the code state "Just like a spreadsheet with multiple worksheets, a SQLite databse can contain multiple tables. In this case three of them are listed in the tbls row in the output above (then lists plots, species, and surveys)" we should change.
With recent updates to `dplyr/dbplyr`, it looks like this is no longer the case when you simply call the db connection. To list the tables and get an output that reflects the text here, use `src_dbi`.
=> update call to "mammals" in sqlite to list tables

05-r-and-databases.Rmd
There are a few outstanding issues in the R and Ecology curriculum noting inconsistencies in usage of read.csv (from base) and read_csv (from readr). read_csv and the readr package are introduced midway through Lesson 3 dplyr. This commit changes read.csv to read_csv in Lesson 5 R and Databases. There are remaining read.csv calls in Lesson 2 Starting with Data and Lesson 3 dplyr, but since these come before the introduction of read_csv they’ll require a more thorough restructuring.
=> change read.csv to read_csv in lesson 5 (R and Databases)

01-intro-to-r.Rmd, 03-dplyr.Rmd, 04-visualization-ggplot2.Rmd
To be consistent with other chapters in the lesson where shortcuts are mentioned for both Windows and Mac OS, added a shortcut for mac for the <- operator for mac in 01-intro-to-r lesson.
A more pedantic issue, specifically mentioned that: "Columns of class character are never converted into factors automatically while loading the dataset."
=> Consistent styling

03-dplyr.Rmd
This is an *optional* pull request. My co-instructor feels strongly, and I feel moderately strongly, that the syntactic sugar of functions without parens in pipelines (e.g. `%>% tally` or `%>% head`), is not worth the extra cognitive load/weirdness.
Arguments for:
- fewer characters to type and read
- learners might see it in existing code bases
Arguments against:
- it's an extra piece. We already have the "functions in pipelines have their first argument inserted automatically" concept established, we don't need the extra shortcut.
=> Bbolker pipe parens

CITATION.Rmd, CONTRIBUTING.Rmd, index.Rmd
Hello :-)
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates some static DOI links.
Cheers!
=> Link DOIs to preferred resolver

02-starting-with-data.Rmd
As discussed in #406, using `class()` in *Starting with data* is not strictly necessary and could be a source of avoidable confusion.
=> Remove reference to `class()`

03-dplyr.Rmd
I add two code-chunks in the "03-dplyr.Rmd" lesson in the **counting** section.
The first chunk shows how to generate **co-occurrence** count between _a set of factors_ (i.e. `sex` and `species`) using `dplyr::count()`, complementing the example of `dplyr::count()` for a single factor (i.e. `sex`). 
The second chunk shows the use of `dplyr::arrange()` to sort the co-occurrence count given _a set of criteria_, complementing the previous example for `dplyr::arrange()` before the **counting** section.
=> Count for combination of factor in the dplyr lesson

05-r-and-databases.Rmd
Just a small typo when creating `species` from the database, it threw an error when a different name was used later on.
=> fixed typo in unique genera code

03-dplyr.Rmd
Explained that `count()` is shorthand for `group_by() %>% summarise(count = n())`, and why it is useful.
Please delete the text below before submitting your contribution.
=> added chunk to section on `counting`

img/joins.svg
This fixes a typo in the schematic representation of `inner_join()` of the `dbplyr` lesson. 
This is mentioned in #454, so should fix that part of the issue.
=> fix typo in joins image

02-starting-with-data.Rmd
This contribution relates to the “starting with Data” section of the Data Analysis and Visualization in R for Ecologists lesion. In this section, trainees are shown how to use the download.file() function to download a dataset for the lesion as below:
`download.file("https://ndownloader.figshare.com/files/2292169", “data/portal_data_joined.csv”).`
As this is the first time trainees will be using this function to download data from the web, I think it should be clarified that this function takes in two arguments; the first argument being the url and the second argument being the destination file. The way the arguments are currently written ("https://ndownloader.figshare.com/files/2292169", “data/portal_data_joined.csv”) it might all be mistaken for one url or two url links separated by a …
=> Specifying_argument_name_with_download.file

00-before-we-start.Rmd
I am a "fan" of enabling the `dependencies` parameter in `install.packages` because I deal with lots of custom packages that depend on lots of other obscure packages, but feel free to remove this as it is not common to enable it.
=> Filled section on how to install tidyverse

03-dplyr.Rmd
Resolves inconsistency in using double quotes when loading a library.
=> addresses issue #543

02-starting-with-data.Rmd
Simple fix of removing an extra period in .Rmd file.
=> typo: removed extra period at end of sentence

04-visualization-ggplot2.Rmd
The former are nice shortcuts, but repetition of a single (and their) "parent" function is probably better for novices.
=> Replace x/ylab() with labs(x/y = ...) to reduce variation / cognitive load

04-visualization-ggplot2.Rmd
Within the ggplot plot facet lesson, there is typo in the comments to group the data by species_id. It should be by genus.
=> fixed typo in ggplot lesson

03-dplyr.Rmd
Dear Carpentries Team,
When going through the split-apply-combine section I found the paragraph where grouping by multiple columns is introduced slightly confusing. First, how to look at the last rows of a data set is not introduced before the section. Second, when talking about "last column" it is not clear if it refers to the original surveys data or the summarized version. And finally I felt like some clarification of why the call to mean results in NaN might be helpful. 
Thanks and best wishes,
Florian
=> Clarification in the split-apply-combine section

00-before-we-start.Rmd
Similar to https://github.com/swcarpentry/python-novice-gapminder/pull/443, but since the resources we mention cover much of the advanced content here, how about we reduce this section to the most relevant part for new learners?
=> Trim "Asking for help" to the essentials

04-visualization-ggplot2.Rmd
Addresses issue with use of `species_id` instead of `genus` in the `ggsave` example at the end of the lesson. Specifically replaces
`facet_wrap(vars(species_id))` with `facet_wrap(vars(genus))`
Fixes Issue 602:  https://github.com/datacarpentry/R-ecology-lesson/issues/602
=> replace species_id with genus in ggsave code

04-visualization-ggplot2.Rmd
Related to #545 & #551. ggplot2's faceting update is 1 year old now. I think mentioning both syntaxes was useful for a time, but going forward, the old one might be more confusing than useful to our learners.
I'm not sure whether that point is now or maybe another year in the future. Please feel free to delay this PR if a longer transition time seems more appropriate.
=> Reduce facet_...() compatibility note to NEWS reference

01-intro-to-r.Rmd, 02-starting-with-data.Rmd
This edit is in response to confusion by learners at a workshop I co-instructed last week. In the previous version, the second example of combining boolean operators:
```
weight_g[weight_g >= 30 & weight_g == 21]
```
returned `#> numeric(0)` because a value cannot be >= 30 AND == 21. Because this is the first exposure to conditionals for most learners, an affirmative example, that doesn't return a NULL value, would be better. I've changed both examples so that all the same boolean operators (`>`, `<`, `<=`, `==`) are still used, and both examples return valid vectors.
=> Clarify logic examples

04-visualization-ggplot2.Rmd
* Remove out-of-context comment about `theme_bw()` in the ggplot2 episode.
* Replace `group_by()` + `tally()` by `count()` in the ggplot2 episode since `tally()` was not previously introduced or used. From what I can see, the grouping in `yearly_sex_counts` is not required, so it felt easier to not introduce a new function.
=> Small fixes to ggplot2 episode

02-starting-with-data.Rmd, 03-dplyr.Rmd, 04-visualization-ggplot2.Rmd, 05-r-and-databases.Rmd
Quoting package names in `library()` is not necessary and disables auto-completion of package names in RStudio.
=> remove quotation marks in `library()` calls

instructor-notes.md
Apparently on some MacOS versions Arial is deactivated. This can cause issues with drawing axis labels in R. I've added instructions how to activate Arial to the instructor notes.
=> closes #628 axis labes not showing when using plot on Mac

instructor-notes.md
@rachellombardi reported a workaround for missing Arial font in ggplots on older Macs. I've added (slightly modified) instructions to the instructor notes.
=> closes #627, add missing font workaround for ggplot to instructor notes

_navbar.html
- Instructor notes cannot be accessed from the course website, only via the [Data Carpentry site](https://datacarpentry.org/lessons/#ecology-workshop). 
- The code handout should not be a top level menu item
- Other carpentry courses have an "Extras" menu item for things like this
This commit addresses these issues by adding an "Extras" dropdown menu item to the navbar, with an entry for the code handout and the instructor notes.
=> add Extras tab for code handout and instructor notes to navbar

02-starting-with-data.Rmd
The contributor pointed out that the distinction between "downloading a file with R" and "loading a file into R" wasn't clear enough. They also argued that `tail()` should be presented to demonstrate the logic of function names in R.
Both valid points, in my opinion. I've addressed both in this commit.
=> addresses #633, clarify download vs. load and add tail function

02-starting-with-data.Rmd
When parsing dates with lubridate, some fail, because two of the dates do not exist (2000-9-31 and 2000-4-31).
This isn't mentioned/explained in the lesson when the warning occurs, but only later. It may be good to acknowledge the warning right away, so no learners get confused about whether they did smething wrong.
=> acknowledge and explain warning in parsing dates when it occurs

04-visualization-ggplot2.Rmd, reference.md
- patchwork has a much simpler syntax., is a tidyverse-adjacent package, and (arguably) the future of arranging ggplots
- added installation instructions for the package, fixed a code error  in the example (`labs()` was added twice to the 1st plot)  and reduced the complexity of the syntax to better highlight the important parts (shorter variable name, fewer linebreaks)
- gave "exporting plots" a separate headline, because it really is a separate section.
- the example now stacks plots vertically, which looks nicer (less crowded) when teaching using a low res screen / projector
=> Use patchwork instead of gridExtra to arrange plots, improve example

02-starting-with-data.Rmd
when the 7th column is a factor vector, the result has two elements, although 3 were requested, because one element is blank. With the 6th column this is not the case.
Also changed "elements" to "rows" for consistency.
closes #586
=> closes #586 confusing example

CONTRIBUTING.Rmd
- some contributors add "carpentries checkout contribution" or similar to their issue titles. This is unnecessary clutter in the issues list. I thought it might help to point out in the contribution guidelines that this is not needed.
- I also noticed that some issues would be very simple pull requests and would like to encourage contributors to commit their issues as pull requests. I find the Github Desktop app extremely helpful (and fun to use) and think it would be worth mentioning it.
- Some issues here are actually multipleissues in one. I suggest reminding contributors to open one issue per problem.
=> add info on submitting issues to contributing.RMD

00-before-we-start.Rmd, instructor-notes.md
It's worthwhile to point out in the instructor notes that R <4.0.0 might cause problems.
I've also added the verison info of RSQlite to the `sessionInfo()` in 'before we start.
This probably closes #640
=> Add info about R 4.0 to instructor notes and RSQLite package version to "before we start"

03-dplyr.Rmd
The verb "Select" should not be used to refer to an operation made by `dplyr::filter()` because these two functions are often mixed up. I've proposed an alternative.
=> Do not refer to "select" for dplyr::filter

instructor-notes.md
Closes #682 
Adds note about getting incorrect number of rows when using `read.csv()` instead of `read_csv()`
=> Adds notice about using the incorrect data import function

instructor-notes.md
Clarified in [instructor notes](https://github.com/datacarpentry/R-ecology-lesson/blob/main/instructor-notes.md) that if final result of `surveys_complete` has incorrect number of rows, then students likely used `read.csv()` instead of `read_csv()` as noted in issue #682
=> clarified effect of using incorrect import function in instructor notes

02-starting-with-data.Rmd
This is my attempt at rewriting the section around subsetting to consider the more consistent behavior of tibbles, which is what our novices will be principally using. 
There is a call-out that this behavior should only be expected when working with tibbles on line 289. I agree that it's not worth diving into the differences between base data frames and tibbles at this level, but I do want to at least flag "this is not universally true." If this feels likely to confuse, though, happy to remove it.
=> Update subsetting for tibbles (#680)

instructor-notes.md
There used to be a separate R script with all the required packages that is now part of the instructor notes.  This PR removes a dead link to that script from the instructor notes and adds an internal link to a list of these packages in the same document.
closes #713
=> fix broken link in instructor notes

05-r-and-databases.Rmd
The challenge starting in line 374 requests the number of rodents observed in each plot, in each year. However, the dplyr syntax answer only groups by taxa and year. I have added 'plot_id' to line 398, so that the output matches the prompt. 
In addition, the code chunks starting in line 396 and 449 use 'tally', which I replaced with 'tally()' to match the tidyverse style guide.
=> Match challenge answer to prompt & style fix

04-visualization-ggplot2.Rmd
Closes #738
There was leftover code from previous version, using  `grid.arrange()` to combine plots. This has now been replaced with patchwork syntax. 
I've also modified the exported plot and renamed variables in the section on patchwork, so that the two sections are more consistent.
=> Fix Exporting plots code

02-starting-with-data.Rmd
Minor changes to the "Working with dates section". 
closes #730
closes #678
**Details:**
- Remove "As recommended earlier in this lesson, dates should be stored with one component per column". This wasn't  recommended earlier in the lesson and I don't think this way to store dates should be recommended. I believe this closes #730. The other issue brought up in 730 (recommend CSV editor) has been settled by discussion.
- mention other lubridate functions . I think this closes #678. I kept it more general than suggested by @ramay If we want to introduce another specific lubridate function, we could do so as part of a new challenge (see #606)
=> modification to working with dates section

CITATION.Rmd
To be consistent with [The Carpentries style guide](https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html#oxford-comma), use the Oxford comma.  
Also fixes spelling of name (ç not c ).
=> correct name spelling; use Carpentries style guide

00-before-we-start.Rmd
removes second mentio of the same link
Fixes #753
=> Streamline bullets at end of "Before we start" episode

00-before-we-start.Rmd, 01-intro-to-r.Rmd, 03-dplyr.Rmd, 04-visualization-ggplot2.Rmd, 05-r-and-databases.Rmd
This PR addresses issue #759. Specifically, I have tried to reword sentences using easy, easier, simple or just. With my replacement I sought to emphasize how the concepts taught help/assist learners in what they aim to do and better explain what the effect of using a specific command is to illustrate the usage. 
Occasionally, I felt that the sentences using 'easy' were redundant or didn't provide additional information. I deleted them in those cases. 
Please ignore the removed trailing whitespaces, unfortunately I didn't see those diffs before commiting. They don't have an effect on the rendered output.
=> Issue 759 avoid easy

01-intro-to-r.Rmd
Replaced broken link for R syntax differences examples, as raised in issue https://github.com/datacarpentry/R-ecology-lesson/issues/754.
=> fix broken link as in issue 754

00-before-we-start.Rmd
I fixed the broken link for the Rstudio cheatsheet to the published link that works.
This new location is the location referred to as published in the original  repos readme.
=> fixed broken link

02-starting-with-data.Rmd
Added a note clarifying the use of view() vs View(). This fixes issue #788.
Also moved read_csv note closer to where the read_csv function was used in the text.
=> Added note about view() vs View()

_site.yml, before_body.html
This adds a banner to the lesson that announces its place in the beta phase of The Workbench and points people to the snapshot at https://preview.carpentries.org/R-ecology-lesson
**Please merge this on Monday, 2022-10-17**
=> [Workbench Beta] Pre-beta banner 

.github/workflows/deploy.yml
This PR does two things:
1. it prevents building to gh-pages from pull requests by adding a
control statement to the last step in the workflow
2. it make sure the workflow can run by pointing to the correct version
in the r-lib action
This will fix #822
=> prevent building to gh-pages on PR; update action

episodes/04-visualization-ggplot2.Rmd
This was a bug from the transition. See https://github.com/ropensci/tinkr/issues/99
This will fix #859
=> fix strikethrough that should have been subscript

episodes/00-before-we-start.Rmd
Coming from https://github.com/datacarpentry/R-ecology-lesson/pull/869#issuecomment-1662632569, I'm getting messages from other people that this link is broken.
This pr will fix the link in the text.
=> fix link to code handout

CONTRIBUTING.Rmd, README.md, episodes/00-before-we-start.Rmd
The Carpentries recently updated their Slack domain URL and invite app URL. This PR updates the links to match the new domains.
=> Update slack links

renv/activate.R, renv/profiles/lesson-requirements/renv.lock
I've run the package update manually because the automated workflow was having trouble after the release of {renv} 1.0.0.
This brings in updates to 44 packages. Please wait for the output to run and then check for any new errors, warnings or surprising output changes.
```
- askpass         [1.1 -> 1.2.0]
- broom           [1.0.4 -> 1.0.5]
- bslib           [repo: RSPM -> CRAN; ver: 0.4.2 -> 0.5.1]
- cpp11           [0.4.3 -> 0.4.6]
- curl            [repo: RSPM -> CRAN; ver: 5.0.0 -> 5.0.2]
- dbplyr          [2.3.2 -> 2.3.3]
- digest          [repo: RSPM -> CRAN; ver: 0.6.31 -> 0.6.33]
- dplyr           [1.1.2 -> 1.1.3]
- evaluate        [repo: RSPM -> CRAN; ver: 0.20 -> 0.21]
- fontawesome     [0.5.1 -> 0.5.2]
- fs              [1.6.2 -> 1.6.3]
- gargle          [1.4.0 -> 1.5.2]
- …
```
=> update 44 packages

index.Rmd
Adds an Instructor Note encouraging Instructors to try teaching [the alternative version of the lesson](https://carpentries-incubator.github.io/R-ecology-lesson-alternative/) which is currently [in beta testing](https://carpentries.org/blog/2023/07/r-ecology-alt-beta/). 
The @datacarpentry/curriculum-advisors-ecology are hoping to receive more feedback from Instructors before they make a final decision on whether to adopt the new lesson into the curriculum.
=> Encourage Instructors to try teaching the alternative lesson in beta

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, index.Rmd
The @datacarpentry/curriculum-advisors-ecology [recently agreed to adopt the redesigned version of this lesson](https://carpentries.org/blog/2024/03/dc-r-ecology-adoption/) (<https://datacarpentry.org/r-ecology-lesson-alternative/>). This PR adds notices to REAMDE.md, index.Rmd, and issue and PR templates notifying visitors of the scheduled change.
=> Add replacement notice

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This reverts commit 8afa6ccfee166d3973e4db8016510b5e84416cda, since the updated version of the lesson was adopted earlier this week.
=> Remove PR & issue templates warning of scheduled replacement

config.yaml, episodes/working-with-data.Rmd
One URL and the `source` parameter in `config.yaml` were incorrect since #887 was merged.
=> update source URL

learners/setup.md
Updated to reflect changes suggested in #894
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the …
=> remove mentions of lubridate from setup instructions

config.yaml
This repository was not configured for the lesson to be tracked by our web analytics. This PR updates the config to enable this, as well as filling in the missing metadata fields for lesson URL and language
=> Configure for Carpentries Matomo tracking

README.md
The README file lists the lesson maintainers. I've updated this list with the new maintainer team and their GitHub links.
=> Update README.md with new maintainers

episodes/visualizing-ggplot.Rmd
This ensures we don't get unnecessary diffs when doing the monthly package update.
It is fine to have this in an included = FALSE chunk as we don't mind learners getting a different output. The only goal is facilitating infrastructure maintenance.
=> Set seed at the start of the ggplot2 episode
